### ISSUE TITLE
Error publishing results to Projektor server. axios.create is not a function

### ISSUE THREAD

**Issue by hobbs131** [craigatk/projektor#1181]
Hello again @craigatk!

Since updating the server to v4.33.0 and the Node script to v3.11.0 and then v3.12.0, we've been seeing this error below.

![Screenshot 2023-11-28 at 12 21 15 PM](https://github.com/craigatk/projektor/assets/60115853/91c7a8f4-f811-4a87-993c-910606d69f84)

Thanks again for all the work on this, and sorry it took so long to provide an update!

**Comment by craigatk** [comment]
Thanks for the heads up about that error! I'll investigate 👍

**Comment by craigatk** [comment]
I'll close this issue for now, but if it happens again please feel free to re-open the issue :)
